@baseURL = http://localhost:5000

### Service Test Route
GET {{baseURL}}/

### Authentication Service
# @name auth
POST {{baseURL}}/login
Content-Type: application/json
Accept: application/json
{
  "email": {{$processEnv USER_EMAIL}},
  "password": {{$processEnv USER_PASSWORD}},
}

### Variable Response
@accessToken = {{auth.response.body}}

### Category Fetch Route
GET {{baseURL}}/categories

### Single Subcategory Fetch
GET {{baseURL}}/subcategory/4

### Subcategories Fetch Route
GET {{baseURL}}/subcategories

##########################
##### Product Routes #####
##########################

###
GET {{baseURL}}/products

###
GET {{baseURL}}/products?page=3

### View a Single Product
GET {{baseURL}}/product/2

### Create a New Product
POST {{baseURL}}/product
Content-Type: application/json
# Authorization: Bearer {{accessToken}}

{
  "prod_title": ,
  "description": ,
  "prod_condition": ,
  "listed_price": ,
  "quantity": ,
  "category_name": "",
  "subcategory_name": "",
}

### Update a Product
PUT {{baseURL}}/product/2
Content-Type: application/json

{
  "tag_label": "#apple, #appleProduct"
}

### Delete a Product
DELETE {{baseURL}}/product/1

#######################
##### User Routes #####
#######################

### Fetch User Details
GET {{baseURL}}/user/10


##############################
##### Transaction Routes #####
##############################
